#!/usr/bin/env python3
"""
Module 0-async_comprehension
"""

from typing import List
from 0-async_generator import async_generator


async def async_comprehension() -> List[float]:
    """
    Coroutine that collects 10 random numbers from async_generator using an
      async comprehension.

    This coroutine will use an asynchronous list comprehension to collect 10
      random float numbers generated by async_generator, then return the
        list of these numbers.

    Returns:
        List[float]: A list of 10 random float numbers collected
          from async_generator.
    """
    return [number async for number in async_generator()]
